export const SET_LIST_TYPE = "SET_LIST_TYPE";
export const FETCH_ARTISTS = "FETCH_ARTISTS";
export const FETCH_ARTISTS_SUCCESS = "FETCH_ARTISTS_SUCCESS";
export const FETCH_ARTISTS_FAILURE = "FETCH_ARTISTS_FAILURE";

export const FETCH_TRACKS = "FETCH_TRACKS";
export const FETCH_TRACKS_SUCCESS = "FETCH_TRACKS_SUCCESS";
export const FETCH_TRACKS_FAILURE = "FETCH_TRACKS_FAILURE";

export const SELECT_ITEM = "SELECT_ITEM";
export const UNSELECT_ITEM = "UNSELECT_ITEM";
export const CLEAR_SELECTED_ITEMS = "CLEAR_SELECTED_ITEMS";

export const SET_TIME_RANGE = "SET_TIME_RANGE";

export const FETCH_RECOMMENDATIONS = "FETCH_RECOMMENDATIONS";
export const FETCH_RECOMMENDATIONS_SUCCESS = "FETCH_RECOMMENDATIONS_SUCCESS";
export const FETCH_RECOMMENDATIONS_FAILURE = "FETCH_RECOMMENDATIONS_FAILURE";
export const CLEAR_RECOMMENDATIONS = "CLEAR_RECOMMENDATIONS";

export const SET_VIEW = "SET_VIEW";

export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";

export const CREATE_PLAYLIST = "CREATE_PLAYLIST";
export const CREATE_PLAYLIST_SUCCESS = "CREATE_PLAYLIST_SUCCESS";
export const CREATE_PLAYLIST_ERROR = "CREATE_PLAYLIST_ERROR";

export const SET_USER_DATA = "SET_USER_DATA";
